### ISSUE TITLE
order of termination calls is important?

### ISSUE THREAD

**Issue by Connoropolous** [staltz/callbag-take#6]
https://github.com/staltz/callbag-take/blob/13326c2ce99165dabefca666681047615505bab6/index.js#L22-L23

I just had a little issue with this code where I was using `callbag-take` within `callbag-concat-map` and `callbag-take` terminates the sink before the source, meaning that it moved on to the next item in `concatMap` before finishing up with the source given to `callbag-take`. 

I switched the order of these two lines and it worked. Is that bad? Good? Is that a general improvement for this code, or would it be case by case?

**Comment by staltz** [comment]
Hmm, good find! I'd gladly accept a PR for this. A test case would be wonderful, but not a big deal if there isn't one.

**Comment by Connoropolous** [comment]
cool, good to know. 
I'd like to get to the level of comprehension to be able to quickly add a test for this, but I'm not there, so I'm going to take you up on the 'not a big deal'
